Launcher3: Import updated Pokemon Unite vector
The current one is non-valid and causes:
java.lang.IllegalArgumentException: R is not a valid verb. Failure occurred at position 2 of path: STRING_TOO_LARGE

Credits: TeamFiles Icons[1]

[1]: https://t.me/modulesrepo/3625

Change-Id: I5c1750d0e15142988351d45c6e15b65805a9782b